---
title: "CLARA Analysis"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE, warning=FALSE}
#library(rstudioapi)
#setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

if (!require('jtools')) install.packages('jtools'); library('jtools')
if (!require('stats')) install.packages('stats'); library('stats')
if (!require('Hmisc')) install.packages('Hmisc'); library('Hmisc')
if (!require('ggplot2')) install.packages('ggplot2'); library('ggplot2')
if (!require('olsrr')) install.packages('olsrr'); library('olsrr')
if (!require('corrplot')) install.packages('corrplot'); library('corrplot')


```

```{r}
#read in data
AoA <- read.csv("Dale_ORourke_AoA.csv", header = TRUE)
Concrete <- read.csv("Brysbaert_Kuperman_Concrete.csv", header = TRUE)
Valence <- read.csv("Warriner_Valence.csv", header = TRUE)

#remove all columns but word and rating
AoA_test <- AoA[, c(1, 3)]
AoA_rate <- AoA[, c(1, 4)]
Concrete <- Concrete[, c(1,3)]
Valence <- Valence[, c(2:3)]

#take min values for unique items in AoA test based norms
low_AoA_test <- aggregate(AoAtestbased ~ Word, AoA_test, min)
max_AoA_test <- aggregate(AoAtestbased ~ Word, AoA_test, max)
AoA_rate_unique <- unique(AoA_rate)
colnames(low_AoA_test) <- c("Word", "AoA_test_min")
colnames(max_AoA_test) <- c("Word", "AoA_test_max")

#merge unique AoA test-based min and max values with concreteness and AoA ratings to see availability
AoA_all <- merge(low_AoA_test, max_AoA_test)

#merge unique AoA test-based min and max values with concreteness to see availability
AoA_Conc <- merge(AoA_all, Concrete, all.x = TRUE)
AoA_Conc_narm <- na.omit(AoA_Conc)

#merge unique AoA test-based min and max values with AoA ratings-based to see availability
AoA_Rate <- merge(AoA_all, AoA_rate_unique, all.x = TRUE)
AoA_Rate_narm <- na.omit(AoA_Rate)

#merge unique AoA test-based min and max values with valence to see availability
AoA_Val <- merge(AoA_all, Valence, all.x = TRUE)
AoA_Val_narm <- na.omit(AoA_Val)

#merge unique AoA test-based min and max values with concreteness and valence to see availability
AoA_regression <- merge(AoA_all, Concrete, all.x = TRUE)
AoA_regression <- merge(AoA_regression, Valence, all.x = TRUE)
AoA_regression_narm <- na.omit(AoA_regression)
sample <- nrow(AoA_regression_narm)
print(sample)

#look correlations between lowest AoA meaning test-based and concreteness and valence
AoAtestmin_Concrete_corr <- cor.test(AoA_Conc_narm$AoA_test_min, AoA_Conc_narm$Conc.M)
AoAtestmin_AoArate_corr <- cor.test(AoA_Rate_narm$AoA_test_min, AoA_Rate_narm$AoArating)
AoAtestmin_Val_corr <- cor.test(AoA_Val_narm$AoA_test_min, AoA_Val_narm$V.Mean.Sum)

print(AoAtestmin_Concrete_corr)
print(AoAtestmin_Val_corr)

#Scatterplot of AoA testbased and Concreteness ratings
attach(AoA_Conc_narm)
plot(Conc.M, AoA_test_min, xlab = "Concreteness", ylab = "Test-based AoA", pch=20)
abline(lm(Conc.M~AoA_test_min), col="red")

#Corrplot matrix
library(corrplot)
M <- cor(AoA_regression[c(2, 4, 5)], use = "pairwise.complete.obs")
corrplot.mixed(M)
```

```{r}
#Run regression using using concreteness and valence to predict test-based AoA
fit <- lm(AoA_test_min ~ Conc.M*V.Mean.Sum, data = AoA_regression_narm)
summary(fit)

#Plot concreteness and valence interaction
CV_plot <-interact_plot(model = fit, pred = Conc.M, modx = V.Mean.Sum)
print(CV_plot)

#see model summary with b coefficients
summ(fit, digits = 3)

#see model summary with beta coefficients 
summ(fit, scale = TRUE, transform.response = TRUE, digits = 3)

##Check part and partial correlations
ols_correlations(fit)
```

```{r}
#Reduce dataframe to only abstract words (items with concreteness rating less than 3)
AoA_abstract <- AoA_regression_narm[AoA_regression_narm$Conc.M < 3,]

#Run polynomial regression using valence to predict test-based AoA with second-order (quadratic) term
fit_abstract2 <- lm(AoA_test_min ~ poly(V.Mean.Sum,2), data = AoA_abstract)
summary(fit_abstract2)

#see model summary with b coefficients
summ(fit_abstract2, digits = 3)

#see model summary with beta coefficients 
summ(fit_abstract2, scale = TRUE, transform.response = TRUE, digits = 3)

##Check part and partial correlations
ols_correlations(fit_abstract2)

#Plot quadratic relationship
Valplot <-ggplot(AoA_abstract, aes(x = V.Mean.Sum, y=AoA_test_min)) + geom_point(color = "grey", size = .5, alpha = .5) + stat_smooth(se = T, method = 'lm', formula = y~poly(x,2), color = "red") + theme_classic() + labs(x = "Valence", y = "Test-based AoA") + ggtitle("Abstract words") + theme(plot.title = element_text(hjust = 0.5))

#View plot
print(Valplot)

#Save png of plot to working directory
ggsave("Valplot.png", width = 5, height = 3)

```

```{r}
#Reduce dataframe to only concrete words (items with concreteness rating greater than 3)
AoA_concrete <- AoA_regression_narm[AoA_regression_narm$Conc.M > 3,]

#Run polynomial regression using valence to predict test-based AoA with second-order (quadratic) term
fit_concrete2 <- lm(AoA_test_min ~ poly(V.Mean.Sum,2), data = AoA_concrete)
summary(fit_concrete2)

#see model summary with b coefficients
summ(fit_concrete2, digits = 3)

#see model summary with beta coefficients 
summ(fit_concrete2, scale = TRUE, transform.response = TRUE, digits = 3)

##Check part and partial correlations
ols_correlations(fit_concrete2)

#Plot quadratic relationship
CValplot <-ggplot(AoA_concrete, aes(x = V.Mean.Sum, y=AoA_test_min)) + geom_point(color = "grey", size = .5, alpha = .5) + stat_smooth(se = T, method = 'lm', formula = y~poly(x,2), color = "red") + theme_classic() + labs(x = "Valence", y = "Test-based AoA") + ggtitle("Concrete words") + theme(plot.title = element_text(hjust = 0.5))

#View plot
print(CValplot)

#Save png of plot to working directory
ggsave("ConcreteValplot.png", width = 5, height = 3)
```

